/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mv_motors;

import java.math.BigDecimal;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import mv_motors.controllers.VeiculosJpaController;
import mv_motors.entities.Veiculos;
import mv_motors.controllers.ModelosJpaController;
import mv_motors.entities.Modelos;

/**
 *
 * @author caiov
 */
public class CadastroVeiculos extends javax.swing.JFrame {

    /**
     * Creates new form Veiculo
     */
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("MV_MotorsPU");
    VeiculosJpaController veiculoController = new VeiculosJpaController(emf);
    ModelosJpaController modelosController = new ModelosJpaController(emf);
    private final List<JTextField> veiculoFields;

    /**
     * Creates new form CadastroCliente
     */
    public CadastroVeiculos() {
        initComponents();

        // Inicializar a lista de campos DEPOIS de initComponents()
        veiculoFields = Arrays.asList(
                textField_placa, // Placa
                textField_complementos,
                textField_quilometragem,
                textField_preco,
                textField_ano,
                textField_documento
        );

        carregarModelosNoComboBox();
        atualizarTabela();

        // Desativar botões de remover e atualizar inicialmente
        button_remover.setEnabled(false);
        button_atualizar.setEnabled(false);
    }

    private void carregarModelosNoComboBox() {
        DefaultComboBoxModel<Modelos> model = new DefaultComboBoxModel<>();
        try {
            List<Modelos> modelos = modelosController.findModelosEntities();
            for (Modelos m : modelos) {
                model.addElement(m);
            }
            comboBox_modelo.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar modelos: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    public void limpar() {

        textField_id.setText(""); // Placa
        textField_complementos.setText("");
        textField_quilometragem.setText("");
        textField_preco.setText("");
        textField_ano.setText("");
        textField_documento.setText("");

        // Limpar seleção do ComboBox (opcional, pode ser o primeiro item)
        if (comboBox_modelo.getItemCount() > 0) {
            comboBox_modelo.setSelectedIndex(0);
        }

        atualizarTabela();

        button_inserir.setEnabled(true);
        button_remover.setEnabled(false);
        button_atualizar.setEnabled(false);
    }

    private void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) table_veiculo.getModel();
        model.setRowCount(0); // Limpa a tabela

        try {
            List<Veiculos> veiculos = veiculoController.findVeiculosEntities();

            for (Veiculos veiculo : veiculos) {
                Object[] linha = {
                    veiculo.getIdVeiculo(),
                    veiculo.getIdModelo(),
                    veiculo.getComplementos(),
                    veiculo.getQuilometragem(),
                    veiculo.getPreco(),
                    veiculo.getAno(),
                    veiculo.getDocumento(),
                    veiculo.getPlaca(),};
                model.addRow(linha);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar veículos: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); // Para depuração
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_veiculo = new javax.swing.JTable();
        textField_id = new javax.swing.JTextField();
        textField_complementos = new javax.swing.JTextField();
        textField_quilometragem = new javax.swing.JTextField();
        textField_preco = new javax.swing.JTextField();
        textField_ano = new javax.swing.JTextField();
        textField_documento = new javax.swing.JTextField();
        button_inserir = new javax.swing.JButton();
        button_limpar = new javax.swing.JButton();
        button_remover = new javax.swing.JButton();
        button_atualizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        textField_placa = new javax.swing.JTextField();
        comboBox_modelo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Veiculos");

        jLabel1.setText("ID Veiculo");

        jLabel2.setText("Modelo:");

        jLabel3.setText("Complementos:");

        jLabel4.setText("Quilometragem:");

        jLabel5.setText("Preço:");

        jLabel6.setText("Ano:");

        jLabel7.setText("Documento:");

        table_veiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idVeiculo", "idModelo", "Complementos", "Quilometragem", "Preço", "Ano", "Documento", "Placa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_veiculo.getTableHeader().setReorderingAllowed(false);
        table_veiculo.setUpdateSelectionOnSort(false);
        table_veiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_veiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_veiculo);

        textField_id.setToolTipText("Identificador único do veículo no sistema.");
        textField_id.setEnabled(false);
        textField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_idActionPerformed(evt);
            }
        });

        textField_complementos.setToolTipText("Informações adicionais ou opcionais sobre o veículo.");

        textField_quilometragem.setToolTipText("Distância total percorrida pelo veículo (em km).");

        textField_preco.setToolTipText("Valor de venda do veículo.");

        textField_ano.setToolTipText("Ano de fabricação ou modelo do veículo.");
        textField_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_anoActionPerformed(evt);
            }
        });

        textField_documento.setToolTipText("Número do documento relacionado ao veículo (como Renavam).");

        button_inserir.setText("Inserir");
        button_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_inserirActionPerformed(evt);
            }
        });

        button_limpar.setText("Limpar");
        button_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_limparActionPerformed(evt);
            }
        });

        button_remover.setText("Remover");
        button_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_removerActionPerformed(evt);
            }
        });

        button_atualizar.setText("Atualizar");
        button_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_atualizarActionPerformed(evt);
            }
        });

        jLabel8.setText("Placa:");

        textField_placa.setToolTipText("Placa de identificação veicular.");

        comboBox_modelo.setToolTipText("Selecione o modelo do veículo.");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textField_id, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(textField_documento, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(textField_ano)
                            .addComponent(textField_preco)
                            .addComponent(textField_quilometragem)
                            .addComponent(textField_complementos)
                            .addComponent(textField_placa)
                            .addComponent(comboBox_modelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_remover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_inserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(101, 101, 101))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_inserir))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboBox_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_limpar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textField_complementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_remover))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textField_quilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_atualizar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textField_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textField_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textField_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textField_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_idActionPerformed

    private void textField_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_anoActionPerformed

    private void button_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_removerActionPerformed
        try {
            if (textField_id.getText().trim().isEmpty()) {
                throw new Exception("Selecione um veículo para remover (informe o Id Veículo).");
            }
            // AQUI ESTÁ O PONTO CRÍTICO:
            // Obtém o IdVeiculo do campo de texto e o converte para Integer
            int idVeiculoParaRemover = Integer.parseInt(textField_id.getText().trim());

            int confirm = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja remover o veículo ID: " + idVeiculoParaRemover + "?", "Confirmar Remoção", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                // Passa o IdVeiculo (Integer) para o método destroy
                veiculoController.destroy(idVeiculoParaRemover); // PK é o IdVeiculo (Integer)
                JOptionPane.showMessageDialog(this, "Veículo ID: " + idVeiculoParaRemover + " removido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                limpar();
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Id Veículo inválido. Digite um número inteiro.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } catch (mv_motors.controllers.exceptions.IllegalOrphanException ex) {
            JOptionPane.showMessageDialog(this, "O veículo não pode ser removido porque já está relacionado a uma venda ou serviço.", "Erro de Integridade", JOptionPane.WARNING_MESSAGE);
            ex.printStackTrace();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao Remover Veículo", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_button_removerActionPerformed

    private void button_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_atualizarActionPerformed
        try {
            // 1. Validar o campo de ID (essencial para localizar o veículo)
            if (textField_id.getText().trim().isEmpty()) {
                throw new Exception("O campo 'Id Veículo' é obrigatório para atualização.");
            }

            // 2. Validar outros campos obrigatórios
            if (textField_placa.getText().trim().isEmpty()
                    || textField_complementos.getText().trim().isEmpty()
                    || textField_quilometragem.getText().trim().isEmpty()
                    || textField_preco.getText().trim().isEmpty()
                    || textField_ano.getText().trim().isEmpty()
                    || textField_documento.getText().trim().isEmpty()) {
                throw new Exception("Preencha todos os campos obrigatórios para atualização!");
            }

            // 3. Validar o ComboBox de Modelo
            if (comboBox_modelo.getSelectedItem() == null) {
                throw new Exception("Selecione um Modelo para o veículo!");
            }

            // 4. Obter o IdVeiculo do campo de texto e encontrar o Veiculos existente
            int idVeiculoParaAtualizar = Integer.parseInt(textField_id.getText().trim());
            Veiculos veiculoExistente = veiculoController.findVeiculos(idVeiculoParaAtualizar);

            if (veiculoExistente == null) {
                throw new Exception("Veículo com Id " + idVeiculoParaAtualizar + " não encontrado para atualização.");
            }

            Modelos modelo = (Modelos) comboBox_modelo.getSelectedItem();

            // 5. Atualizar os atributos do objeto 'veiculoExistente' com os novos dados da GUI
            // Tratamento de formato decimal (substitui vírgula por ponto)
            String precoStr = textField_preco.getText().replace(',', '.');
            String quilometragemStr = textField_quilometragem.getText().replace(',', '.');

            veiculoExistente.setPlaca(textField_placa.getText().trim());
            // Lembre-se: O setter é setFkModelo() e espera um objeto Modelos
            //veiculoExistente.setFkModelo((Modelos) jComboBox1.getSelectedItem()); // Pega o objeto Modelo do ComboBox
            veiculoExistente.setComplementos(textField_complementos.getText().trim());
            //veiculoExistente.setQuilometragem(new BigDecimal(quilometragemStr));
            veiculoExistente.setPreco(new BigDecimal(precoStr));
            veiculoExistente.setAno(Integer.parseInt(textField_ano.getText().trim()));
            veiculoExistente.setDocumento(textField_documento.getText().trim());
            veiculoExistente.setIdModelo(modelo);

            veiculoController.edit(veiculoExistente);

            JOptionPane.showMessageDialog(this, "Veículo ID: " + idVeiculoParaAtualizar + " (Placa: " + veiculoExistente.getPlaca() + ") atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limpar(); // Limpa os campos e atualiza a tabela

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Erro de formato numérico nos campos 'Id Veículo', 'Quilometragem', 'Preço' ou 'Ano'. Verifique se são números válidos.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); // Para depuração
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao Atualizar Veículo", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); // Para depuração
        }
    }//GEN-LAST:event_button_atualizarActionPerformed

    private void button_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_limparActionPerformed
        limpar();
    }//GEN-LAST:event_button_limparActionPerformed

    private void button_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_inserirActionPerformed
        try {
            // Verificação de campos de texto vazios
            for (JTextField field : veiculoFields) {
                if (field.getText().trim().isEmpty()) {
                    throw new Exception("Preencha todos os campos obrigatórios!");
                }
            }

            // Verificação do ComboBox
            if (comboBox_modelo.getSelectedItem() == null) {
                throw new Exception("Selecione um Modelo para o veículo!");
            }

            Modelos modelo = (Modelos) comboBox_modelo.getSelectedItem();

            Veiculos novoVeiculo = new Veiculos(
                    veiculoController.getVeiculosCount(),
                    textField_complementos.getText(),
                    Integer.parseInt(textField_quilometragem.getText()),
                    new BigDecimal(textField_preco.getText()),
                    Integer.parseInt(textField_ano.getText()),
                    textField_documento.getText(),
                    textField_placa.getText(),
                    modelo
            );

            veiculoController.create(novoVeiculo);

            JOptionPane.showMessageDialog(this, "Veículo com placa " + novoVeiculo.getPlaca() + " inserido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limpar();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Erro de formato numérico nos campos 'Quilometragem', 'Preço' ou 'Ano'. Verifique se são números válidos.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao Inserir Veículo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button_inserirActionPerformed

    private void table_veiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_veiculoMouseClicked
        int selectedRow = table_veiculo.getSelectedRow();
        if (selectedRow >= 0) {
            DefaultTableModel model = (DefaultTableModel) table_veiculo.getModel();
            // AQUI ESTÁ A CORREÇÃO: Pega o IdVeiculo (que é Integer) da primeira coluna (índice 0)
            Integer idVeiculoFromTable = (Integer) model.getValueAt(selectedRow, 0);

            try {
                // Passa o IdVeiculo (Integer) para o método findVeiculos
                Veiculos veiculo = veiculoController.findVeiculos(idVeiculoFromTable);

                if (veiculo != null) {
                    textField_id.setText(String.valueOf(veiculo.getIdVeiculo()));
                    textField_placa.setText(veiculo.getPlaca());

                    // Handling the Modelos ComboBox
                    if (veiculo.getIdModelo() != null) {
                        DefaultComboBoxModel<Modelos> cbModel = (DefaultComboBoxModel<Modelos>) comboBox_modelo.getModel();
                        for (int i = 0; i < cbModel.getSize(); i++) {
                            if (cbModel.getElementAt(i).equals(veiculo.getIdModelo())) {
                                comboBox_modelo.setSelectedIndex(i);
                                break;
                            }
                        }
                    } else {
                        comboBox_modelo.setSelectedItem(null);
                    }

                    textField_complementos.setText(veiculo.getComplementos());
                    textField_quilometragem.setText(String.valueOf(veiculo.getQuilometragem()));
                    textField_preco.setText(String.valueOf(veiculo.getPreco()));
                    textField_ano.setText(String.valueOf(veiculo.getAno()));
                    textField_documento.setText(veiculo.getDocumento());
                    button_remover.setEnabled(true);
                    button_atualizar.setEnabled(true);
                    // ... (outros campos que você possa ter)
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao carregar dados do veículo selecionado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_table_veiculoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_atualizar;
    private javax.swing.JButton button_inserir;
    private javax.swing.JButton button_limpar;
    private javax.swing.JButton button_remover;
    private javax.swing.JComboBox<mv_motors.entities.Modelos> comboBox_modelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_veiculo;
    private javax.swing.JTextField textField_ano;
    private javax.swing.JTextField textField_complementos;
    private javax.swing.JTextField textField_documento;
    private javax.swing.JTextField textField_id;
    private javax.swing.JTextField textField_placa;
    private javax.swing.JTextField textField_preco;
    private javax.swing.JTextField textField_quilometragem;
    // End of variables declaration//GEN-END:variables
}
