/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mv_motors;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import mv_motors.controllers.ClienteJpaController;
import mv_motors.controllers.VeiculosJpaController;
import mv_motors.controllers.VendaJpaController;
import mv_motors.entities.Cliente;
import mv_motors.entities.Venda;
import mv_motors.entities.Veiculos;

/**
 *
 * @author vchri
 */
public class CadastroVenda extends javax.swing.JFrame {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("MV_MotorsPU");
    VendaJpaController vendaController = new VendaJpaController(emf);
    VeiculosJpaController veiculoController = new VeiculosJpaController(emf);
    ClienteJpaController clienteController = new ClienteJpaController(emf);
    
    private final List<JTextField> vendaList;
    private final String[] formasPagamento = {
        "Financiamento",
        "Credito a vista",
        "Credito parcelado",
        "Debito a vista",       
        "Debito parcelado",
        "Pix",
        "Cedula"
    };
    
    String pattern = "MM/dd/yyyy";
    DateFormat df = new SimpleDateFormat(pattern);
    
    /**
     * Creates new form CadastroVenda
     */
    public CadastroVenda() {
        initComponents();
        atualizarTabela();
        
        vendaList = Arrays.asList(
                textField_documento,
                textField_dataVenda,
                textField_dataRetirada              
        );
        
        for (int i = 0; i < formasPagamento.length; i++)
            comboBox_formaPagamento.addItem(formasPagamento[i]);
    }
    
    private void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) table_vendas.getModel();

        model.setRowCount(0); // limpa a tabela

        try {
            List<Venda> vendas = vendaController.findVendaEntities();

            for (Venda venda : vendas) {
                String linha[] = {
                    String.valueOf(venda.getIdVenda()),
                    venda.getDocCompraVenda(),
                    df.format(venda.getDataVenda()),
                    df.format(venda.getDataRetirada()),
                    venda.getFormaPagamento(),                   
                    venda.getFkVeiculos().toString(),
                    venda.getFkComprador().getCpf()
                };

                model.addRow(linha);
            }
            
            atualizarComboBox();
            
            if (comboBox_veiculo.getItemCount() > 0 && comboBox_cliente.getItemCount() > 0)
                button_inserir.setEnabled(true);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void atualizarComboBox() {
        List<Veiculos> veiculos = veiculoController.findVeiculosEntities();
        List<Cliente> clientes = clienteController.findClienteEntities();      

        DefaultComboBoxModel<Veiculos> veiculoModel = new DefaultComboBoxModel();       
        for (Veiculos veiculo : veiculos)
            veiculoModel.addElement(veiculo);
        comboBox_veiculo.setModel(veiculoModel);
        
        DefaultComboBoxModel<Cliente> clienteModel = new DefaultComboBoxModel(); 
        for (Cliente cliente : clientes)
            clienteModel.addElement(cliente);      
        comboBox_cliente.setModel(clienteModel);
    }
    
    private void limpar() {
        textField_idVenda.setText("");
        textField_documento.setText("");
        textField_dataVenda.setText("");
        textField_dataRetirada.setText("");
        comboBox_formaPagamento.setSelectedIndex(0);
        comboBox_veiculo.setSelectedIndex(0);
        comboBox_cliente.setSelectedIndex(0);

        atualizarTabela();

        button_inserir.setEnabled(true);
        button_remover.setEnabled(false);
        button_atualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textField_idVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textField_documento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textField_dataVenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textField_dataRetirada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboBox_formaPagamento = new javax.swing.JComboBox<>();
        comboBox_cliente = new javax.swing.JComboBox<>();
        comboBox_veiculo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_vendas = new javax.swing.JTable();
        button_inserir = new javax.swing.JButton();
        button_limpar = new javax.swing.JButton();
        button_remover = new javax.swing.JButton();
        button_atualizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda");

        jLabel1.setText("ID Venda");
        jLabel1.setToolTipText("Informe o CPF (somente números). Este campo é obrigatório");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textField_idVenda.setToolTipText("Identificador único da venda no sistema.");
        textField_idVenda.setEnabled(false);

        jLabel2.setText("Documento de Compra e Venda");
        jLabel2.setToolTipText("Digite um número de telefone ou outro meio de contato (ex: e-mail ou WhatsApp).");

        textField_documento.setToolTipText("Número do contrato ou documento referente à transação.");

        jLabel3.setText("Data da venda");

        textField_dataVenda.setToolTipText("Data em que a venda foi registrada.");

        jLabel4.setText("Data de retirada");

        textField_dataRetirada.setToolTipText("Data prevista para retirada do veículo pelo cliente.");

        jLabel5.setText("Forma de Pagamento");

        jLabel6.setText("Cliente (CPF)");

        jLabel7.setText("Veiculo");

        comboBox_formaPagamento.setToolTipText("Método utilizado no pagamento: à vista, parcelado, financiamento etc.");

        comboBox_cliente.setToolTipText("CPF do cliente responsável pela compra.");

        comboBox_veiculo.setToolTipText("Modelo ou ID do veículo vendido.");

        table_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Venda", "Documento Compra e Venda", "Data Venda", "Data Retirada", "Forma de Pagamento", "Veiculo", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_vendas.getTableHeader().setReorderingAllowed(false);
        table_vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_vendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_vendas);

        button_inserir.setText("Inserir");
        button_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_inserirActionPerformed(evt);
            }
        });

        button_limpar.setText("Limpar");
        button_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_limparActionPerformed(evt);
            }
        });

        button_remover.setText("Remover");
        button_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_removerActionPerformed(evt);
            }
        });

        button_atualizar.setText("Atualizar");
        button_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_atualizarActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textField_dataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textField_dataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textField_idVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textField_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(comboBox_formaPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(comboBox_cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboBox_veiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(button_inserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField_idVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField_dataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField_dataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBox_formaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBox_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBox_veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_inserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_remover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_atualizar))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_inserirActionPerformed

        try {
            if (vendaList.stream().anyMatch(v -> v.getText().equals("")))
            throw new Exception("Preencha todos os campos!");
            
            
            Veiculos newVeic = (Veiculos) comboBox_veiculo.getSelectedItem();
            Cliente newCliente = (Cliente) comboBox_cliente.getSelectedItem();

            Venda venda = new Venda(                               
                textField_documento.getText(),                            
                df.parse(textField_dataVenda.getText()),                             
                df.parse(textField_dataRetirada.getText()),                             
                (String)comboBox_formaPagamento.getSelectedItem(),
                newCliente,
                newVeic              
            );

            vendaController.create(venda);

            limpar();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_button_inserirActionPerformed

    private void button_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_limparActionPerformed
        limpar();
    }//GEN-LAST:event_button_limparActionPerformed

    private void button_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_removerActionPerformed
        try
        {
            int idRemover = Integer.parseInt(textField_idVenda.getText());
                     
            int confirm = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja remover o veículo ID: " + idRemover + "?", "Confirmar Remoção", JOptionPane.YES_NO_OPTION);
            
            //System.out.println("id que chegou: " + idRemover);
            
            if (confirm == JOptionPane.YES_OPTION) {
                // Passa o IdVeiculo (Integer) para o método destroy
                vendaController.destroy(idRemover);
                JOptionPane.showMessageDialog(this, "Veículo ID: " + idRemover + " removido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                limpar();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_button_removerActionPerformed

    private void button_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_atualizarActionPerformed
        try
        {
            if (vendaList.stream().anyMatch(v -> v.getText().equals("")))
            throw new Exception("Preencha todos os campos!");

            Venda venda = vendaController.findVenda(Integer.parseInt(textField_idVenda.getText()));

            venda.setDocCompraVenda(textField_documento.getText());
            venda.setDataVenda(df.parse(textField_dataVenda.getText()));
            venda.setDataRetirada(df.parse(textField_dataRetirada.getText()));
            venda.setFormaPagamento((String)comboBox_formaPagamento.getSelectedItem());
            venda.setFkVeiculos((Veiculos)comboBox_veiculo.getSelectedItem());
            venda.setFkComprador((Cliente)comboBox_cliente.getSelectedItem());

            vendaController.edit(venda);

            JOptionPane.showMessageDialog(
                this,
                "Produto: " + textField_idVenda.getText() + " alterado com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE
            );

            limpar();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_button_atualizarActionPerformed

    private void table_vendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_vendasMouseClicked
        DefaultTableModel model = (DefaultTableModel) table_vendas.getModel();
        
        if (evt.getClickCount() == 2)
        {
            int row = table_vendas.getSelectedRow();
            
            // Veiculo
            int veiculoId = Integer.parseInt(model.getValueAt(row, 5).toString().split(" \\| ")[0]);           
            Veiculos veiculo = veiculoController.findVeiculos(veiculoId); 
            
            // Cliente
            Cliente cliente = clienteController.findCliente(model.getValueAt(row, 6).toString());
            
            // atualizando tabela...
            textField_idVenda.setText(model.getValueAt(row, 0).toString());
            textField_documento.setText(model.getValueAt(row, 1).toString());
            textField_dataVenda.setText(model.getValueAt(row, 2).toString());
            textField_dataRetirada.setText(model.getValueAt(row, 3).toString());           
            comboBox_formaPagamento.setSelectedItem(model.getValueAt(row, 4).toString());            
            comboBox_veiculo.setSelectedItem(veiculo);
            comboBox_cliente.setSelectedItem(cliente);

            // buttons
            button_atualizar.setEnabled(true);
            button_remover.setEnabled(true);
            button_inserir.setEnabled(false);
        }
    }//GEN-LAST:event_table_vendasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_atualizar;
    private javax.swing.JButton button_inserir;
    private javax.swing.JButton button_limpar;
    private javax.swing.JButton button_remover;
    private javax.swing.JComboBox<Cliente> comboBox_cliente;
    private javax.swing.JComboBox<String> comboBox_formaPagamento;
    private javax.swing.JComboBox<Veiculos> comboBox_veiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_vendas;
    private javax.swing.JTextField textField_dataRetirada;
    private javax.swing.JTextField textField_dataVenda;
    private javax.swing.JTextField textField_documento;
    private javax.swing.JTextField textField_idVenda;
    // End of variables declaration//GEN-END:variables
}
