/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mv_motors;

import java.awt.Color;

/**
 *
 * @author vchri
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        //this.getContentPane().setBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_venda = new javax.swing.JButton();
        button_cliente = new javax.swing.JButton();
        button_veiculo = new javax.swing.JButton();
        button_modelo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MV Motors");
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_venda.setBackground(new java.awt.Color(255, 255, 255));
        button_venda.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        button_venda.setForeground(new java.awt.Color(0, 0, 0));
        button_venda.setText("Venda");
        button_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_vendaActionPerformed(evt);
            }
        });
        getContentPane().add(button_venda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 200, 50));

        button_cliente.setBackground(new java.awt.Color(255, 255, 255));
        button_cliente.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        button_cliente.setForeground(new java.awt.Color(0, 0, 0));
        button_cliente.setText("Cliente");
        button_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(button_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 200, 50));

        button_veiculo.setBackground(new java.awt.Color(255, 255, 255));
        button_veiculo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        button_veiculo.setForeground(new java.awt.Color(0, 0, 0));
        button_veiculo.setText("Veiculo");
        button_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_veiculoActionPerformed(evt);
            }
        });
        getContentPane().add(button_veiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 200, 50));

        button_modelo.setBackground(new java.awt.Color(255, 255, 255));
        button_modelo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        button_modelo.setForeground(new java.awt.Color(0, 0, 0));
        button_modelo.setText("Modelo");
        button_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_modeloActionPerformed(evt);
            }
        });
        getContentPane().add(button_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 200, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clienteActionPerformed
        CadastroCliente clienteWindow = new CadastroCliente();
        clienteWindow.setVisible(true);
    }//GEN-LAST:event_button_clienteActionPerformed

    private void button_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_veiculoActionPerformed
        CadastroVeiculos veiculoWindow = new CadastroVeiculos();
        veiculoWindow.setVisible(true);
    }//GEN-LAST:event_button_veiculoActionPerformed

    private void button_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_modeloActionPerformed
        CadastroModelos modeloWindow = new CadastroModelos();
        modeloWindow.setVisible(true);
    }//GEN-LAST:event_button_modeloActionPerformed

    private void button_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_vendaActionPerformed
        CadastroVenda vendaWindow = new CadastroVenda();
        vendaWindow.setVisible(true);
    }//GEN-LAST:event_button_vendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cliente;
    private javax.swing.JButton button_modelo;
    private javax.swing.JButton button_veiculo;
    private javax.swing.JButton button_venda;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
